optimizer: {
  type: AdamW,
  kwargs: {
    lr: 0.0003, # Adjusted learning rate
    weight_decay: 0.03 # Adjusted weight decay
  }
}

scheduler: {
  type: CosLR,
  kwargs: {
    epochs: 300,
    initial_epochs: 20 # Adjusted initial epochs
  }
}

dataset: {
  train: { _base_: cfgs/dataset_configs/ModelNet40.yaml, 
           others: {subset: 'train'}},
  val: { _base_: cfgs/dataset_configs/ModelNet40.yaml, 
         others: {subset: 'test'}},
  test: { _base_: cfgs/dataset_configs/ModelNet40.yaml, 
          others: {subset: 'test'}}
}

model: {
  NAME: PointTransformer,
  trans_dim: 384, 
  depth: 12, 
  drop_path_rate: 0.2, # Adjusted drop path rate
  cls_dim: 40, 
  num_heads: 6,
  group_size: 32, 
  num_group: 64, 
  encoder_dims: 256
}

npoints: 2048 # Adjusted number of points
total_bs: 64 # Adjusted batch size
step_per_update: 1
max_epoch: 300
grad_norm_clip: 5 # Adjusted gradient clipping

consider_metric: CDL1
